name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/hello-world-action
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
